version: '3.8'
services:
  infraweb:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
